USER_NAME := apedley
CONSOLE_ENABLE = yes
COMMAND_ENABLE = no
RGB_MATRIX_ENABLE = no
AUDIO_ENABLE = yes
ENCODER_ENABLE = no
HAPTIC_ENABLE = no


CAPS_WORD_ENABLE = no

DYNAMIC_MACRO_ENABLE = no

ifeq ($(strip $(OLED_ENABLE)), yes)
  SRC += oled_display.c
	OLED_DRIVER = SSD1306
	WPM_ENABLE = yes
endif

# POINTING_DEVICE_ENABLE = yes
# POINTING_DEVICE_DRIVER = cirque_pinnacle_i2c
# POINTING_DEVICE_DRIVER = pimoroni_trackball

QUANTUM_PAINTER_ENABLE = yes
QUANTUM_PAINTER_DRIVERS += gc9a01_spi

ifeq ($(strip $(QUANTUM_PAINTER_ENABLE)), yes)
  SRC += lcd_display.c
	WPM_ENABLE = yes
	QUANTUM_PAINTER_LVGL_INTEGRATION = yes
	QUANTUM_PAINTER_DRIVERS = gc9a01_spi
endif

AP_KEYMAP_OVERLAY_ENABLE = no
AP_RGB_INDICATORS_ENABLE = no
RAW_ENABLE = yes

SPLIT_KEYBOARD = no
