#OPT_DEFS += -DDYNAMIC_KEYMAP_LAYER_COUNT=1
KEYBOARD_SHARED_EP = yes
VIA_ENABLE = no
LTO_ENABLE = yes

MIDI_ENABLE = no
MOUSEKEY_ENABLE = yes
# CAPS_WORD_ENABLE = yes

# DYNAMIC_MACRO_ENABLE = yes
# LEADER_ENABLE = yes
# COMBO_ENABLE = no
# TAP_DANCE_ENABLE = yes
# KEY_OVERRIDE_ENABLE = yes
