/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define RGB_MATRIX_KEYPRESSES

// #define DYNAMIC_MACRO_NO_NESTING

// #define MIDI_ADVANCED

// #define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD
// #define GRAVE_ESC_SHIFT_OVERRIDE

// #define LEADER_PER_KEY_TIMING
// #define LEADER_NO_TIMEOUT
// #define LEADER_TIMEOUT 400


// #define TAPPING_TERM 175
