OPT_DEFS += -DDYNAMIC_KEYMAP_LAYER_COUNT=5

VIA_ENABLE = no
LTO_ENABLE = yes

MIDI_ENABLE = no

#CAPS_WORD_ENABLE = yes

# DYNAMIC_MACRO_ENABLE = yes
# LEADER_ENABLE = yes
# COMBO_ENABLE = no
# TAP_DANCE_ENABLE = yes
# KEY_OVERRIDE_ENABLE = yes


CONSOLE_ENABLE = yes
COMMAND_ENABLE = yes

RAW_ENABLE = yes
