USER_NAME := apedley

ifeq ($(strip $(OLED_ENABLE)), yes)
  SRC += oled_display.c
endif
WPM_ENABLE = yes

CONSOLE_ENABLE = yes
COMMAND_ENABLE = yes

SPLIT_POINTING_ENABLE = yes
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pimoroni_trackball
RAW_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
TAP_DANCE_ENABLE = yes
CAPS_WORD_ENABLE = yes

COMBO_ENABLE = yes

MOUSEKEY_ENABLE = yes

REPEAT_KEY_ENABLE = yes

TRI_LAYER_ENABLE = yes
#define TRI_LAYER_ADJUST_LAYER 5
# KEYBOARD_SHARED_EP = yes
