

#pragma once
#define DYNAMIC_KEYMAP_LAYER_COUNT 6

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 450U
#ifdef AUDIO_ENABLE
#endif /// AUDIO_ENABLE

#ifdef HAPTIC_ENABLE
#endif /// HAPTIC_ENABLE


#ifdef RGB_MATRIX_ENABLE

  // #define FP_LAYER_LIGHTING_DYNAMIC_BASE_LAYER_DISABLE
  // #define FP_STARTUP_ANIMATION_DISABLE

  // #define FP_LAYER_LIGHTING_MODE RGB_MATRIX_BAND_VAL
  // #define FP_LAYER_LIGHTING_MODE RGB_MATRIX_RAINBOW_MOVING_CHEVRON


  // #undef ENABLE_RGB_MATRIX_ALPHAS_MODS
  #undef ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
  // #undef ENABLE_RGB_MATRIX_BREATHING
  #undef ENABLE_RGB_MATRIX_BAND_SAT
  // #undef ENABLE_RGB_MATRIX_BAND_VAL
  #undef ENABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
  #undef ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
  #undef ENABLE_RGB_MATRIX_BAND_SPIRAL_SAT
  #undef ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL
  #undef ENABLE_RGB_MATRIX_CYCLE_ALL
  #undef ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
  #undef ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
  #undef ENABLE_RGB_MATRIX_CYCLE_OUT_IN
  #undef ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
  // #undef ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
  #undef ENABLE_RGB_MATRIX_DUAL_BEACON
  #undef ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
  #undef ENABLE_RGB_MATRIX_CYCLE_SPIRAL
  // #undef ENABLE_RGB_MATRIX_RAINBOW_BEACON
  #undef ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS
  #undef ENABLE_RGB_MATRIX_RAINDROPS
  #undef ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
  // #undef ENABLE_RGB_MATRIX_TYPING_HEATMAP
  #undef ENABLE_RGB_MATRIX_DIGITAL_RAIN
  // #undef ENABLE_RGB_MATRIX_SOLID_REACTIVE
  #undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
  #undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE
  #undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
  #undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
  #undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
  // #undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
  #undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
  #undef ENABLE_RGB_MATRIX_SPLASH
  #undef ENABLE_RGB_MATRIX_MULTISPLASH
  #undef ENABLE_RGB_MATRIX_SOLID_SPLASH
  #undef ENABLE_RGB_MATRIX_SOLID_MULTISPLASH



  #define FP_STARTUP_ANIMATION_DISABLE

  // FP_HSV_LIME Saturated
  #define FP_LAYER_LIGHTING_HUE_1 63, 255, 255

  // FP_HSV_LAVENDER Saturated
  #define FP_LAYER_LIGHTING_HUE_2 184, 255, 255

  // FP_HSV_MELON Saturated
  #define FP_LAYER_LIGHTING_HUE_3 0, 220, 255

  #define FP_LAYER_LIGHTING_HUE_4 HSV_RED

  #define FP_LAYER_LIGHTING_HUE_5 HSV_CYAN

  #define FP_LAYER_LIGHTING_AUTO_MOUSE_ENABLE

  // I don't think this ever happens but I'm leaving it just in case.
  // Even though there is no way that I will remember this when my keeb is suddenly pink.

  #define FP_LAYER_LIGHTING_AUTO_MOUSE_HUE HSV_MAGENTA


  // #undef RGB_MATRIX_MAXIMUM_BRIGHTNESS
  // #undef RGB_MATRIX_STARTUP_VAL

  #define RGB_MATRIX_UNDERGLOW_MAXIMUM_BRIGHTNESS 135

  // define RGB_MATRIX_UNDERGLOW_SOLID_COLOR
  #define RGB_MATRIX_UNDERGLOW_HUE 191
  #define RGB_MATRIX_UNDERGLOW_VAL 115


#endif /// RGB_MATRIX_ENABLE

#ifdef ENCODER_ENABLE
  // #undef ENCODERS_PAD_A
  // #undef ENCODERS_PAD_B

  // #define ENCODERS_PAD_A { GP8 }
  // #define ENCODERS_PAD_B { GP7 }
  #define FP_ENC_0_LAYER_SCROLL_WHEEL 1
  #define FP_ENC_0_LAYER_SUPER_CTRL_TAB 2
  #define FP_ENC_0_LAYER_DPI_POINTING 5
  #define FP_ENC_0_LAYER_ZOOM 3
  #define FP_ENC_0_LAYER_PGUP_PGDN 6
  // #undef FP_ENC_1_LAYER_SUPER_TAB
  // #undef FP_ENC_1_LAYER_VOLUME

  #define FP_ENC_1_LAYER_SCROLL_WHEEL 0
  #define FP_ENC_1_LAYER_SUPER_CTRL_TAB 3
  #define FP_ENC_1_LAYER_DPI_POINTING 2
  #define FP_ENC_1_LAYER_ZOOM 1
  #define FP_ENC_1_LAYER_PGUP_PGDN 5
  #define FP_ENC_1_LAYER_SUPER_TAB 4

  // #define FP_ENC_1_LAYER_VOLUME 4
  // #define FP_ENC_1_LAYER_SCROLL_WHEEL 2
  // #define FP_ENC_1_LAYER_SUPER_TAB 4
#endif

#ifdef OLED_ENABLE
  #define I2C_DRIVER I2CD1
  #define SPLIT_OLED_ENABLE
  #define SPLIT_WPM_ENABLE
  #define SPLIT_LED_STATE_ENABLE
  #define SPLIT_ACTIVITY_ENABLE

  // #define I2C1_SDA_PIN GP2
  // #define I2C1_SCL_PIN GP3
  #define OLED_DISPLAY_128X64
  #define OLED_DISPLAY_ADDRESS 0x3C
#endif


#ifdef POINTING_DEVICE_ENABLE

  #define FP_POINTING_ACCELERATION_ENABLE

  #define FP_POINTING_SCROLLING_DPI 4

  // #define FP_POINTING_SNIPING_LAYER 2
  // #define FP_POINTING_SNIPING_LAYER_ENABLE


  #define CIRQUE_PINNACLE_TAP_ENABLE
  #define CIRQUE_PINNACLE_SECONDARY_TAP_ENABLE
  // #define POINTING_DEVICE_GESTURES_SCROLL_ENABLE

  #define POINTING_DEVICE_DEBUG
  #define POINTING_DEVICE_AUTO_MOUSE_ENABLE
  #define AUTO_MOUSE_DEFAULT_LAYER 5
  #define AUTO_MOUSE_TIME 650
  #define MOUSE_EXTENDED_REPORT
#endif // POINTING_DEVICE_ENABLE

#ifdef QUANTUM_PAINTER_ENABLE


  /* SPI pins */
  #define SPI_DRIVER SPID0

  /* LCD Configuration */
  #define LCD_DC_PIN GP4
  #define LCD_RST_PIN GP5
  #define LCD_CS_PIN GP6


  #ifndef LCD_ACTIVITY_TIMEOUT
  #    define LCD_ACTIVITY_TIMEOUT 30000
  #endif // LCD_ACTIVITY_TIMEOUT


  // #define QUANTUM_PAINTER_SUPPORTS_256_PALETTE TRUE
  // #define QUANTUM_PAINTER_LOAD_FONTS_TO_RAM TRUE
  // #define QUANTUM_PAINTER_PIXDATA_BUFFER_SIZE 128
  // #define QUANTUM_PAINTER_DEBUG

#endif // QUANTUM_PAINTER_ENABLE
// Tap-hold configuration for home row mods.
#define TAPPING_TERM 180
#define IGNORE_MOD_TAP_INTERRUPT
#define PERMISSIVE_HOLD
#define TAPPING_FORCE_HOLD_PER_KEY

#define AUTO_SHIFT_TIMEOUT 175
#define NO_AUTO_SHIFT_SPECIAL
#define NO_AUTO_SHIFT_ALPHA
