

#pragma once

#ifdef AUDIO_ENABLE

  #define AP_STARTUP_FLOW_DOWN H__NOTE(_E6), Q__NOTE(_REST), Q__NOTE(_C6), H__NOTE(_G5), Q__NOTE(_A5), H__NOTE(_D5), H__NOTE(_E5), H__NOTE(_C5),
  #undef STARTUP_SONG
  #define STARTUP_SONG SONG(AP_STARTUP_FLOW_DOWN)
#endif /// AUDIO_ENABLE

#ifdef HAPTIC_ENABLE
#endif /// HAPTIC_ENABLE


#ifdef RGB_MATRIX_ENABLE
  #define FP_LAYER_LIGHTING_DYNAMIC_BASE_LAYER_DISABLE
  #define FP_STARTUP_ANIMATION_DISABLE
  #define FP_LAYER_LIGHTING_MODE RGB_MATRIX_BAND_VAL
//   #define FP_LAYER_LIGHTING_MODE RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#endif /// RGB_MATRIX_ENABLE
