CONSOLE_ENABLE = yes
COMMAND_ENABLE = yes
RGB_MATRIX_ENABLE = yes
AUDIO_ENABLE = yes
ENCODER_ENABLE = yes
HAPTIC_ENABLE = yes

AUTO_SHIFT_ENABLE = yes

CAPS_WORD_ENABLE = yes

DYNAMIC_MACRO_ENABLE = yes

FP_CIRQUE_BOTH = yes

AP_KEYMAP_OVERLAY_ENABLE = yes
AP_RGB_INDICATORS_ENABLE = yes
RAW_ENABLE = yes
