
#pragma once


#ifdef RGB_MATRIX_ENABLE

  #define WS2812_PIO_USE_PIO1
  #define WS2812_DI_PIN GP0
  #define RGB_MATRIX_LED_COUNT 32

  #define RGB_MATRIX_KEYPRESSES
  #define RGB_MATRIX_FRAMEBUFFER_EFFECTS

  #define ENABLE_RGB_MATRIX_ALPHAS_MODS

  #define ENABLE_RGB_MATRIX_BREATHING

  #define RGB_MATRIX_MAXIMUM_BRIGHTNESS 255 /* The maximum brightness level */

#endif // RGB_MATRIX_ENABLE



#ifdef OLED_ENABLE
  #define I2C_DRIVER I2CD1
  #define I2C1_SDA_PIN GP2
  #define I2C1_SCL_PIN GP3
#endif

#undef QUICK_TAP_TERM
#undef TAPPING_TERM
#define TAPPING_TERM 175

#define PERMISSIVE_HOLD
#define TAPPING_TOGGLE 2
