#ifdef POINTING_DEVICE_ENABLE
  #define I2C_DRIVER I2CD1
  #define I2C1_SDA_PIN GP2
  #define I2C1_SCL_PIN GP3
  // #define CIRQUE_PINNACLE_DIAMETER_MM 35

  // #define CIRQUE_PINNACLE_ADDR 0x2A
  // #define CIRQUE_PINNACLE_TAP_ENABLE

  // #define CIRQUE_PINNACLE_POSITION_MODE CIRQUE_PINNACLE_RELATIVE_MODE
  #define MOUSE_EXTENDED_REPORT
  #define PIMORONI_TRACKBALL_ADDRESS 0x0A
  // #define PIMORONI_TRACKBALL_SCALE 5
  #define POINTING_DEVICE_ROTATION_90
  #define POINTING_DEVICE_DEBUG
#endif
