// Copyright 2023 Andrew Pedley (@apedley)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

/*
 * Feature disable options
 *  These options are also useful to firmware size reduction.
 */

/* disable debug print */
//#define NO_DEBUG

/* disable print */
//#define NO_PRINT

/* disable action features */
//#define NO_ACTION_LAYER
//#define NO_ACTION_TAPPING
//#define NO_ACTION_ONESHOT

// RGB Matrix
// #define ENABLE_RGB_MATRIX_ALPHAS_MODS
// #define ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
// #define ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
// #define ENABLE_RGB_MATRIX_BREATHING
// #define ENABLE_RGB_MATRIX_BAND_SAT
// #define ENABLE_RGB_MATRIX_BAND_VAL
// #define ENABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
// #define ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
// #define ENABLE_RGB_MATRIX_BAND_SPIRAL_SAT
// #define ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL
// #define ENABLE_RGB_MATRIX_CYCLE_ALL
// #define ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
// #define ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
// #define ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
// #define ENABLE_RGB_MATRIX_CYCLE_OUT_IN
// #define ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
// #define ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
// #define ENABLE_RGB_MATRIX_CYCLE_SPIRAL
// #define ENABLE_RGB_MATRIX_DUAL_BEACON
// #define ENABLE_RGB_MATRIX_RAINBOW_BEACON
// #define ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS
// // enabled only if RGB_MATRIX_FRAMEBUFFER_EFFECTS is defined
// #define ENABLE_RGB_MATRIX_TYPING_HEATMAP
// #define ENABLE_RGB_MATRIX_DIGITAL_RAIN
// // enabled only of RGB_MATRIX_KEYPRESSES or RGB_MATRIX_KEYRELEASES is defined
// #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
// #define ENABLE_RGB_MATRIX_SOLID_REACTIVE
// #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE
// #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
// #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
// #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
// #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
// #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
// #define ENABLE_RGB_MATRIX_SPLASH
// #define ENABLE_RGB_MATRIX_MULTISPLASH
// #define ENABLE_RGB_MATRIX_SOLID_SPLASH
// #define ENABLE_RGB_MATRIX_SOLID_MULTISPLASH

// #define RGB_MATRIX_MAXIMUM_BRIGHTNESS 120
// #define RGB_MATRIX_DEFAULT_VAL RGB_MATRIX_MAXIMUM_BRIGHTNESS
// #define RGB_MATRIX_LED_COUNT 32
// #define RGB_MATRIX_FRAMEBUFFER_EFFECTS
// #define RGB_MATRIX_KEYPRESSES
#define WS2812_PIO_USE_PIO1
#define WS2812_DI_PIN GP0

// #define RGBLED_NUM 32
// #define RGBLIGHT_EFFECT_BREATHING
// #define RGBLIGHT_EFFECT_RAINBOW_MOOD
// #define RGBLIGHT_EFFECT_RAINBOW_SWIRL
// #define RGBLIGHT_EFFECT_LED_TEST
#ifdef RGB_MATRIX_ENABLE

  #define RGB_MATRIX_LED_COUNT 32


  // Remove defaults
  #undef ENABLE_RGB_MATRIX_ALPHAS_MODS
  #undef ENABLE_RGB_MATRIX_BREATHING
  #undef ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL
  #undef ENABLE_RGB_MATRIX_CYCLE_ALL
  #undef ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
  #undef ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
  #undef ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
  #undef ENABLE_RGB_MATRIX_CYCLE_OUT_IN
  #undef ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
  #undef ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
  #undef ENABLE_RGB_MATRIX_CYCLE_SPIRAL
  #undef ENABLE_RGB_MATRIX_DUAL_BEACON
  #undef ENABLE_RGB_MATRIX_RAINBOW_BEACON
  #undef ENABLE_RGB_MATRIX_RAINDROPS
  #undef ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
  #undef ENABLE_RGB_MATRIX_PIXEL_RAIN

  #undef ENABLE_RGB_MATRIX_TYPING_HEATMAP
  #undef ENABLE_RGB_MATRIX_DIGITAL_RAIN

  #undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
  #undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
  #undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
  #undef ENABLE_RGB_MATRIX_SPLASH
  #undef ENABLE_RGB_MATRIX_SOLID_SPLASH

  #define RGB_MATRIX_KEYPRESSES
  #define RGB_MATRIX_FRAMEBUFFER_EFFECTS
  #define RGB_MATRIX_SOLID_REACTIVE_GRADIENT_MODE

  #define ENABLE_RGB_MATRIX_ALPHAS_MODS

  #define ENABLE_RGB_MATRIX_BREATHING
  // #define ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL
  // #define ENABLE_RGB_MATRIX_CYCLE_ALL
  // #define ENABLE_RGB_MATRIX_CYCLE_OUT_IN
  // #define ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
  // #define ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
  // #define ENABLE_RGB_MATRIX_CYCLE_PINWHEEL

  // #define ENABLE_RGB_MATRIX_PIXEL_RAIN
  #define ENABLE_RGB_MATRIX_RAINBOW_BEACON
  #define ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON

  #define ENABLE_RGB_MATRIX_RAINDROPS
  #define ENABLE_RGB_MATRIX_DIGITAL_RAIN

  #define ENABLE_RGB_MATRIX_TYPING_HEATMAP

  #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
  #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
  #define ENABLE_RGB_MATRIX_MULTISPLASH
  #define ENABLE_RGB_MATRIX_SOLID_MULTISPLASH

  #define RGB_MATRIX_MAXIMUM_BRIGHTNESS 255 /* The maximum brightness level */

#endif // RGB_MATRIX_ENABLE


#define I2C_DRIVER I2CD1
#define I2C1_SDA_PIN GP2
#define I2C1_SCL_PIN GP3

#ifdef OLED_ENABLE
#    define OLED_DISPLAY_128X32
#    define OLED_FONT_H "customglcdfont.c"
#endif

#undef QUICK_TAP_TERM
#undef TAPPING_TERM
#define TAPPING_TERM 175

#define PERMISSIVE_HOLD
#define TAPPING_TOGGLE 2
